### PR TITLE
Chapter 5

### PR DESCRIPTION
**Pull request by BologaMarius**

### CODE REVIEW

**Comment by BologaMarius** [comment]
Regarding the whole project  or only about XML part?

**Comment by Alex-Cosma** [comment]
The whole project

**Comment by BologaMarius** [comment]
At the level that I have now in Java, I might say that I agree with you regarding this architecture. Why? It's simple. It looks like each class has it's own predefined role and predefined place in the project. It seems like a pedigree chart starting from a superclass, Animal/Employee defining very abstract concepts, or more general  attributes for all the animals/employees and all the subclasses farther down the hierarchy adds more information, becoming increasingly particular. What I like the most at this architecture is the fact that we can easily extend the project by adding more animals, employees, even more attributes for each of them and it's easy to follow and understand. All this can be done very easily. I can also say that it's a good example for learning, I mean, you see how all the classes band together. At first I did not find very easy to understand that part with the abstract factories,  it looks disorderly , but following the same idea of hierarchy and a little bit of Google , I managed to understand. 
   And as you said-"you’ll see beauty in design at the end" I must admit, even if we are not at the end of the project, that I saw beauty in this architecture.
I'm not sure if you were really expecting this type of opinion, or you were expected a more elevated language, in more programming language terms etc..but I hope you liked it.I hope it wasn't so boring.. Sorry for my formal language.

**Comment by BologaMarius** [comment]
```
 At the level that I have now in Java, I might say that I agree with you regarding this architecture. Why? It's simple. It looks like each class has it's own predefined role and predefined place in the project. It seems like a pedigree chart starting from a superclass, Animal/Employee defining very abstract concepts, or more general attributes for all the animals/employees and all the subclasses farther down the hierarchy adds more information, becoming increasingly particular. What I like the most at this architecture is the fact that we can easily extend the project by adding more animals, employees, even more attributes for each of them and it's easy to follow and understand. All this can be done very easily. I can also say that it's a good example for learning, I mean, you see how all the classes band together. At first I did not find very easy to understand that part with the abstract factories,  it looks disorderly, but following the same idea of hierarchy and a little bit of Google , I managed to understand. 
```

   And as you said-"you’ll see beauty in design at the end" I must admit, even if we are not at the end of the project, that I saw beauty in this architecture.
I'm not sure if you were really expecting this type of opinion, or you were expected a more elevated language, in more programming language terms etc..but I hope you liked it.I hope it wasn't so boring, and sorry for my formal language.

**Comment by Alex-Cosma** [comment]
Your answer is great and no, I didn't expect a more elaborate one. I simply needed some feedback on the project as I simply wrote what I had in mind and you, the students,  were kinda my "test subjects"  (in a very non-evil sort of way)

**Comment by BologaMarius** [comment]
Ok! Thank you  for sparing your precious time and also for your patience. There are not many persons/teachers that would do this. You deserve my respect!

**Pull request merged**
