### PR TITLE
Assignment 2

### PR DESCRIPTION
**Pull request by alexh95**

### CODE REVIEW

**Comment by alexh95** [comment]
I added DIVIDE and ROOTS to the file parser along with the others.

**Comment by Alex-Cosma** [comment]
Other then this, very well done.
But, never forget the [K.I.S.S.](https://en.wikipedia.org/wiki/KISS_principle) principle!

**Comment by alexh95** [comment]
I moved all the computing methods in a different class. I initially kept them in Polynomials because it had visibility over the fields and it kept things simpler. Although it would have been nice it java supported overloading operators.

**Comment by Alex-Cosma** [comment]
But you did not use that visibility over those fields. You simply used the getters/setters from the polynomials received as parameters

**Comment by alexh95** [comment]
I previously used the visibility directly, I only added the getters and setters necessary after I created the new function.

**Comment by alexh95** [comment]
I implemented some sort of singleton pattern, form what I understand it is useful when you try to share a resource (some sort of global scope). So methods are "public" instead of "public static", it gives you the options of not occupying memory unless you want to. Correct me if i'm wrong but I don't see why you wouldn't just use static methods. I implemented it but it does not seem quite relevant in this case.

**Comment by Alex-Cosma** [comment]
The purpose of a Singleton is to ensure a class has only one instance, and provide a global point of access to it. Most of the time the focus is on the single instance point. Imagine if it were called a Globalton. It would sound less appealing as this emphasizes the (usually) negative connotations of a global variable.
Read up [here](http://c2.com/cgi/wiki?SingletonsAreGood)
PS: Nothing you do on these assignments is "relevant" to anything but you learning new things. _Singleton_ is the most basic and easiest of design patterns. I'll introduce more and more as we go on, even 'hiding' some of them at first.

**Comment by Alex-Cosma** [comment]
I am also merging this.

**Pull request merged**
