### PR TITLE
Assignment4

### PR DESCRIPTION
**Pull request by andreeaonaciu**

### CODE REVIEW

**Comment by andreeaonaciu** [comment]
I created a new class for the creation of the animals and employees, so as to keep the main method simpler, and I also tried to do the 5th assignment,but I have some problems with the load method...

**Comment by Alex-Cosma** [comment]
I'm sure you'll figure it out, but if the problems persist, do tell me - I'll take a more _in depth_ look at it.

**Comment by andreeaonaciu** [comment]
Now the load method works for the employees, but doesn't work for the animals, I tried to figure out the error, but I cannot figure it out yet...and I would be grateful if you could give me a hint, please ! I hope it is not a silly mistake...

**Comment by andreeaonaciu** [comment]
Thank you so much ! :) I will try to be more careful next time !!! And to answer your question, if we have no "break" in a switch statement, the compiler will continue to execute the next lines of code until reaching a break statement,or if there is none, until reaching the end of the switch block.

**Comment by Alex-Cosma** [comment]
Glad I could help!

**Comment by Alex-Cosma** [comment]
Well done

**Pull request merged**
