### PR TITLE
Assignment2_2

### PR DESCRIPTION
**Pull request by crinela**
I hope that I have understood correctly the requests

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
You have to write something like this:

```
int initialNumber = 5;
BigDecimal first = new BigDecimal(initialNumber);
// and if you want to change this 'first' in order for it to contain a different number
int differentNumber = 2;
first = new BigDecimal(differentNumber);
```

**Comment by Alex-Cosma** [comment]
And you are perfectly right about the singleton pattern, however, because you used the singleton pattern, could we now remove the `static` modifier from the methods? if yes, why? and if no, why not?

**Comment by Alex-Cosma** [comment]
Well done, merging this.

**Comment by crinela** [comment]
I think that the static modifier should be removed. I do not know If I am right, but I have read the followings: in Java For Dummies, 5th Edition: "Anything that’s declared to
be static belongs to the whole class, not to any particular instance of the
class. When you create the static field, totalOfAverages, you create
just one copy of the field. This copy stays with the entire Players class. No
matter how many instances of the Player class you create — one, nine, or
none — you have just one totalOfAverages field.."
So, if I have used the singleton pattern it is clear that I only have one object, so I do not need the static modifier.

**Comment by Alex-Cosma** [comment]
Yes, you are perfectly right. Even though, if you think about it a bit, they're kinda the same thing (more or less), however, [here](http://javarevisited.blogspot.ro/2013/03/difference-between-singleton-pattern-vs-static-class-java.html) is a nice article about the differences. Anyway, in the context of the small program you created, both approaches could be used. (Personally, I prefer singleton - it's tidier)

**Comment by crinela** [comment]
Thank you for this answer. I know it may sound weird, but my name is not "Pontinteu" is "Potinteu". Is  it possible to change it ?

**Comment by Alex-Cosma** [comment]
You can do that yourself actually. Rename the folder with your name, commit the changes, push them and create a new pull request. After that, I'll merge them.
I'm sorry for misspelling your name :disappointed:

**Comment by crinela** [comment]
I have done all the instructions above. I am very lucky that I can attend this course, misspelling my name is the last problem.

**Pull request merged**
