### PR TITLE
Assignment 4 & 5 & 6

### PR DESCRIPTION
**Pull request by AlexaGh**
Maybe I should've uploaded the assignments at a run, for clearance and to have my mistakes figured and fixed at the right time. Anyway thing is, in part 3 at the switch statement I got a “duplicate case” error and I couldn’t wrap my head around it.. so I commented those cases in order to move on http://i.imgur.com/70MBnQR.jpg (@Reptile and @Birds).  But besides having those cases left out, everything worked nicely. Then I did part 4 and got a null pointer exception (googled it, I know what it means), but only “once and again” (when I want to output the loaded-animalList).  Since I won’t have my laptop for a couple of days, I figured I might as well upload my code and have it looked over – [anyway] I will come back to it and reorganize the code etc; this is only the “rough” and messy version.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
The reason for which you get that `duplicate case` error is because, in the `Constants` you have the following:
`public static final String SeaTurtle = "Nigel";`
`public static final String MoonJellyfish = "Nigel";`
Notice that they both have the same `String` associated to them, `Nigel`. Because of this, the switch statement would not know which branch to execute, the `SeaTurtle` one or  the `MoonJellyfish` one, in case `Nigel` (as as string) decides to 'pop-in' the switch statement.

**Comment by AlexaGh** [comment]
I changed the name of the seaTurtle in seaNigel, check the latest commit.
(and I still got a duplicate case error.. And why do I get that error for
the birds as well?)

**Comment by Alex-Cosma** [comment]
You are missing the point. The problem is not in the variable _name_ but its _contents_. They both contain `"Nigel"` as a string!

**Comment by AlexaGh** [comment]
Aso. I got it, thank you. I will change that as soon as I can.

**Comment by Alex-Cosma** [comment]
Hai că îți explic în română, poate e mai clar.

La linia 32 în `Constants` ai
`public static final String MoonJellyfish = "Nigel";`
Observi că acolo scrie `Nigel`?

La linia 34 din aceeași clasă ai
`public static final String SeaTurtle = "Nigel";`
Din nou, aici e tot `Nigel`.

Dacă am "desface" switch-ul ăla pentru cele 2 constante, ar arăta ceva de genul

```
...
...
        case Constants.Animals.Insects.LadyBug:
            Animal ladyBug = new LadyBug();
            ladyBug.decodeFromXml(element);
            return ladyBug;
        case Constants.Animals.Insects.Spider:
            Animal spider = new Spider();
            spider.decodeFromXml(element);
            return spider;
        case "Nigel":
            Animal seaturtle = new SeaTurtle();
            seaturtle.decodeFromXml(element);
            return seaturtle;
        case "Nigel":
            Animal jellyfish = new MoonJellyfish();
            jellyfish.decodeFromXml(element);
            return jellyfish;
        case Constants.Animals.Aquatics.SeaHorse:
            Animal seahorse = new SeaHorse();
            seahorse.decodeFromXml(element);
            return seahorse;
...
...
```

Am avea 2 case-uri cu același verificare, `"Nigel"`. 
Asta e ca și cum ai scrie

```
if( whatever == 2 ) {
   doSomething();
}
if( whatever == 2) {
   doSomethingElse();
}
```

Diferența e că în Java, compilatorul interpretează chestia asta în switch ca ceva greșit! Problema e că nu ar știi pe care din ramurile din switch să intre pentru că verifică exact același string, și anume "Nigel"!!

Dacă schimbi 
`public static final String MoonJellyfish = "Nigel";`
în
`public static final String MoonJellyfish = "Nigel1";` de exemplu, (sau îl schimbi pe celălalt), nu o să mai ai eroarea aia.

E clar acum?

**Pull request merged**
