### PR TITLE
Zoowsome

### PR DESCRIPTION
**Pull request by BologaMarius**
I  still have work to do on this project, but I'm not sure if I understand very well the task.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
You're on the right path! There are a few general things which need to be taken care of:
- controllers belong in the _controllers_ package. Regardless of what they do, that's where they should stay
- frames/views belong in the _views_ package. Again, regardless of what they do.
- in Eclipse, you can right click your project from the Package Explorer tab and go to `Source` and `Format`. This way, all the files in your project will be nicely formatted and squeaky clean.

**Comment by BologaMarius** [comment]
I've made all the changes except for one. I still don't know how to fetch the animals from the XML file. I'm listing something, but it is not so good. How can I do it? And one more question, how can I print an animal/employee that I've just added?

**Comment by Alex-Cosma** [comment]
As stated in my previous comment, you already have the code to load the animals from the xml inside the `load` method which resides in the `AnimalRepository`. Now you simply need to call this from your `AnimalListController` and then fill the view with this list.

**Comment by Alex-Cosma** [comment]
Your `AnimalListFrame` class could have a method called `printAnimals` which takes as parameter a list of animals. You can then print it in whatever way you want to screen, but I would suggest a table structure (`JTable`, maytbe?)
This is up to you.

**Comment by Alex-Cosma** [comment]
Did I answer your question?

**Comment by BologaMarius** [comment]
Done! Hope is good!

**Comment by BologaMarius** [comment]
And yes, you gave me all the answers I need! Thank you!

**Comment by BologaMarius** [comment]
You're right. I will fix that..

**Comment by BologaMarius** [comment]
If you don't mind,  can I ask you a silly question?! I've done what you asked, but only for CreateAController it works. I used the same code(almost) for the rest of the classes of this kind, but instead of showing me the new data, it shows the animal, with it's predefined name, number of legs etc.Why?!

**Comment by Alex-Cosma** [comment]
Your problem is in loading the elements as they are saved correctly. Debug it!

**Comment by Alex-Cosma** [comment]
(merged this by accident - please create new pull request :disappointed: )

**Pull request merged**
