### PR TITLE
Assignment 4

### PR DESCRIPTION
**Pull request by crinela**

### CODE REVIEW

**Comment by crinela** [comment]
Thank you ! Now some things about constructors are clearer. Also I had no idea about that forum.

**Comment by Alex-Cosma** [comment]
But it has a section of its own [here](https://github.com/JavaSummer/JavaMainRepo)! :smile:

**Comment by crinela** [comment]
I  have tried to solve the fifth assignment and I would like to ask you a question. After I load the animals from the file in a list, if I do not know what it is inside the file, how can I know next in the program the type of each animal.?

**Comment by Alex-Cosma** [comment]
Are you sure you've read all the instructions? There should be a 'disctiminant' field in each node of an animal / employee. That field should dictate what animal you are dealing with. 
Tell me if this does not answer your question. I may not fully understand it.

**Comment by crinela** [comment]
In main after I call the load method, I receive an ArrayList that will contain animals, how can I know in main what type has each animal from the returned list?

**Comment by Alex-Cosma** [comment]
Why would you need this?

**Comment by crinela** [comment]
Honestly, I was just curious, I am sorry to have bothered you. Is is correct my fifth assignment?,

**Comment by Alex-Cosma** [comment]
Ooooh! But don't be sorry! You have not bothered me at all - I was just wondering why you would need such a thing. 
Unfortunately, it won't be so easy to find out, however, you can simply use the `instanceof` operator

**Comment by Alex-Cosma** [comment]
But yes, the assignment is good! 
Ps: sorry the delayed response

**Comment by crinela** [comment]
I used to write if (ok == true)  in Pascal and it is a little hard for me to change it now, but I will try.

**Comment by crinela** [comment]
When I tried to display the results of the repoA.load method I was wondering it there is a simple way of knowing what type of animals is, without seeing the file,  Thank you for saying about the instanceof operator, I think that it may be very useful in the future. I ask this kind of questions to find out things like this one, again thank you for your answers.

**Comment by Alex-Cosma** [comment]
It's great that you asked, feel free to do it any time.

**Pull request merged**
