### PR TITLE
I have almost finished 2 more assignments: 6&7

### PR DESCRIPTION
**Pull request by Ranapop**
I still haven't done the twist for assignment 7.. I am really not sure if it's well done up till there. Anyways, looking forward to hearing(reading) your opinion on it, same as always :)

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Your list looks good but I don't see any creation forms. [Here's](http://s27.postimg.org/7am64ekur/Capture.png) a glimpse of how it could look like although you can do it differently of course

**Comment by Alex-Cosma** [comment]
You'll have to excuse the delay.
There are some things which still don't work that well. For example, I wanted to add a bird, completed the form with the following attributes:
Name: A
Number of legs: 3
Maintenance cost: 4
Dancer percent: 51
Average flight altitude: 22
Does it migrate: yes

And then clicked on `Duck` (or you can click on `Pigeon` or `Sparrow`, it doesn't really matter). I don't get any message that something went wrong, but in the console I am getting:

```
java.lang.NumberFormatException: null
    at java.lang.Integer.parseInt(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at javasmmr.zoowsome.services.factories.animalFactories.BirdFactory.getAnimal(BirdFactory.java:11)
    at javasmmr.zoowsome.controllers.BirdController$ButtonActionListener.actionPerformed(BirdController.java:63)
```

**Comment by Ranapop** [comment]
well.... i tried it and it works... and yeah... i do have to press enter once completeing each field.... and yes... i should prevent the user from entering the data incorrectly, maybe make some error message pop :? anyways, i will revise it asap, or change this on the twist :D

**Comment by Alex-Cosma** [comment]
Oh, I did not press enter for each field! Why would one need to do that? simply fetch the values on submit

**Pull request merged**
