### PR TITLE
Assignment 1

### PR DESCRIPTION
**Pull request by alexh95**

### CODE REVIEW

**Comment by alexh95** [comment]
In 1.1 - how could I find the overflow value for the long type?
In 1.2 - Is there really no way to run the constructor without creating an object of the class? since all the fields of the class are static anyway and I use them with the class name direcly.
Also in the description of 1.2, is n (from O(n)) 4000000 in this case?

**Comment by Alex-Cosma** [comment]
Alex, I'll look over them tomorrow afternoon.

**Comment by Alex-Cosma** [comment]
So, overflow for int/long
`Integer.MIN_VALUE / Integer.MAX_VALUE`
`Long.MIN_VALUE / Long.MAX_VALUE`
Simple as that.

**Comment by Alex-Cosma** [comment]
No, however, if you want something static initialized read up [here](https://docs.oracle.com/javase/tutorial/java/javaOO/initial.html) on the  `Static Initialization Blocks` section. I think it's what you need!

**Comment by Alex-Cosma** [comment]
I see you jumped ahead to classes and so on. Well done!
Keep up the good work

**Pull request merged**
