### PR TITLE
Chapter 7 Assignment

### PR DESCRIPTION
**Pull request by uivlis**
I still need to work on the "Save and Exit" button. Also, maybe on the layout for the "List" button.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Ok so it's fine if you want to add predefined attributes to the created animals, however, I was thinking of a form structure in which you have a label and a text box for each attribute of each type of animal. In this way, I could fill in the values for each attribute myself and not have them predefined.
This way you can use a radio button for selection animals from a species and not have 3 buttons there each time.

**Comment by georgebejan** [comment]
Good work so far but I have some observations:
1. You have to load animals and employees from xml files on application startup. If you start the application and check Animals.xml file you'll see that it empty (even if you had values in it before starting the application). Take care not to reinitialize the xml files at application startup.
2. 'Save and exit' button saves the entities to xml files but does not exit the application.
3. For listing all animals I suggest using a table (take a look at [JTable](https://docs.oracle.com/javase/tutorial/uiswing/components/table.html))
4. Regarding the user experience: when creating a new animal/employee the text field has some default value (e.g: enter name). If I select an animal type then the default name is set (this is not the desired behavior). Also when I click on an animal type I have no idea that the animal was created (you have to dispose that frame or show a notice that a new entry was created).
5. On each controller when you create a new entry you have the following flow: create new entry from GUI fields, load all entities from repository, add the newly created entity to repository, save the entity to repository. You can try a different approach here: How about creating a new method in repository for adding new entities? And all that logic can be done there  (adding and saving to repository)

I hope these observations help you

**Comment by uivlis** [comment]
thank you for your observations

**Comment by georgebejan** [comment]
Good job :+1:

**Pull request merged**
