### PR TITLE
Assignment 2.2

### PR DESCRIPTION
**Pull request by AlexaGh**
It took me that long to upload this because I was still trying to get the division of the polynomials done. (Although there will appear changes in Assignment 2.1 there is nothing new to check, as my division of polynomials method does not work and I only have it commented -that's all there is "new" in Assignment 2.1). I will come back to the division "problem", but in the meantime I will continue with assignment 3.

### CODE REVIEW

**Comment by AlexaGh** [comment]
I'm not sure where I should leave my comment so you ca get a notification e-mail. Hope this will do.

**Comment by AlexaGh** [comment]
Uhm, I don't like this for loop any better as I create a matrix with the same element(s). I tried something like 
BigDecimal x = new BigDecimal(10);
BigDecimal y = new BigDecimal(15); 
and in the for loop something like matrix[i][j] = new BigDecimal(x.add(y)); and all sort of other combinations but none worked. (I wanted to at least increase the elements I have in the matrix)

**Comment by AlexaGh** [comment]
I think this will do.

**Comment by Alex-Cosma** [comment]
merging this

**Pull request merged**
